# Cloudflare D1 Configuration for ADHD Learning RPG
name = "adhd-learning-rpg"
main = "functions/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "adhd-learning-rpg"
database_id = "your-d1-database-id"  # Replace with your actual D1 database ID

# Pages configuration for deployment
[env.production]
vars = { NODE_ENV = "production" }

# Local development configuration
[env.development]
vars = { NODE_ENV = "development" }

[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "adhd-learning-rpg-preview"
database_id = "2584cb5f-3257-49ec-b084-0bba78ba291e"
