# Cloudflare Pages + D1 + Enhanced Infrastructure
name = "gadejo-github-io"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Pages build configuration
pages_build_output_dir = "dist"

# Default D1 Database (Production)
[[d1_databases]]
binding = "DB"
database_name = "adhd-learning-rpg"
database_id = "2f5d953f-d723-4aa2-b8a8-8634799e67e2"

# Global variables for all environments
[vars]
APP_NAME = "ADHD Learning RPG"
APP_VERSION = "4.0.0"
SUPPORT_EMAIL = "support@adhdlearningrpg.com"

# ---------- PRODUCTION (main branch) ----------
[env.production]
[env.production.vars]
NODE_ENV = "production"
API_BASE_URL = "https://gadejo-github-io.pages.dev"
ENVIRONMENT = "production"
DEBUG_MODE = "false"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "900" # 15 minutes
SESSION_DURATION = "604800" # 7 days
MAX_UPLOAD_SIZE = "5242880" # 5MB

# Production Database
[[env.production.d1_databases]]
binding = "DB"
database_name = "adhd-learning-rpg"
database_id = "2f5d953f-d723-4aa2-b8a8-8634799e67e2"

# Production KV Namespaces
[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "27468ac52229485495c8ab85119482ff"
preview_id = "27468ac52229485495c8ab85119482ff"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "477349b4795e40969d15253cc42f2461"
preview_id = "477349b4795e40969d15253cc42f2461"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "5417e5e76c5a4a969d07deca94ba716b"
preview_id = "5417e5e76c5a4a969d07deca94ba716b"

# ---------- PREVIEW (PRs/preview deploys) ----------
[env.preview]
[env.preview.vars]
NODE_ENV = "preview"
API_BASE_URL = "https://preview.gadejo-github-io.pages.dev"
ENVIRONMENT = "preview"
DEBUG_MODE = "true"
RATE_LIMIT_REQUESTS = "50"
RATE_LIMIT_WINDOW = "900"
SESSION_DURATION = "86400" # 1 day for preview
MAX_UPLOAD_SIZE = "2097152" # 2MB for preview

# Preview Database
[[env.preview.d1_databases]]
binding = "DB"
database_name = "adhd-learning-rpg-preview"
database_id = "2584cb5f-3257-49ec-b084-0bba78ba291e"

# Preview KV Namespaces (same as production for now)
[[env.preview.kv_namespaces]]
binding = "SESSIONS"
id = "27468ac52229485495c8ab85119482ff"
preview_id = "27468ac52229485495c8ab85119482ff"

[[env.preview.kv_namespaces]]
binding = "CACHE"
id = "477349b4795e40969d15253cc42f2461"
preview_id = "477349b4795e40969d15253cc42f2461"

[[env.preview.kv_namespaces]]
binding = "RATE_LIMIT"
id = "5417e5e76c5a4a969d07deca94ba716b"
preview_id = "5417e5e76c5a4a969d07deca94ba716b"